# Generated by Django 4.2.6 on 2023-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_finalmenu_nesting_menu_nesting_submenu_nesting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmenu',
            name='nesting',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nesting',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='nesting',
            field=models.IntegerField(),
        ),
    ]
