# Generated by Django 4.2.6 on 2023-10-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_finalmenu_nesting_alter_menu_nesting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmenu',
            name='nesting',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='nesting',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='nesting',
        ),
    ]
